# Generated by Django 2.2.6 on 2020-09-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150)),
                ('blog_description', models.TextField(max_length=500)),
                ('blog_author', models.CharField(default='Anonymous', max_length=200)),
                ('blog_date', models.DateTimeField(auto_now=True)),
                ('blog_image', models.ImageField(upload_to='blogapp/images')),
                ('blog_url', models.URLField(blank=True)),
            ],
        ),
    ]
